// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFEDnamoNhZXUm_HqW2MiYobIut29z3Y',
    appId: '1:397259271643:web:d534a67a31779cb571cbfe',
    messagingSenderId: '397259271643',
    projectId: 'lastproject-ee0c2',
    authDomain: 'lastproject-ee0c2.firebaseapp.com',
    storageBucket: 'lastproject-ee0c2.appspot.com',
    measurementId: 'G-T6C2KKPLX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6baqEh82W9tOr0hsJC8wTsrC9he-JwaI',
    appId: '1:397259271643:android:f2082caec362337e71cbfe',
    messagingSenderId: '397259271643',
    projectId: 'lastproject-ee0c2',
    storageBucket: 'lastproject-ee0c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_7vUeQqU0LFRgFk4-SakDIk3XfzXS7M',
    appId: '1:397259271643:ios:4c6a00b3bc77139271cbfe',
    messagingSenderId: '397259271643',
    projectId: 'lastproject-ee0c2',
    storageBucket: 'lastproject-ee0c2.appspot.com',
    iosBundleId: 'com.example.lastproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq_7vUeQqU0LFRgFk4-SakDIk3XfzXS7M',
    appId: '1:397259271643:ios:4c6a00b3bc77139271cbfe',
    messagingSenderId: '397259271643',
    projectId: 'lastproject-ee0c2',
    storageBucket: 'lastproject-ee0c2.appspot.com',
    iosBundleId: 'com.example.lastproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFEDnamoNhZXUm_HqW2MiYobIut29z3Y',
    appId: '1:397259271643:web:ef3232770e76e9df71cbfe',
    messagingSenderId: '397259271643',
    projectId: 'lastproject-ee0c2',
    authDomain: 'lastproject-ee0c2.firebaseapp.com',
    storageBucket: 'lastproject-ee0c2.appspot.com',
    measurementId: 'G-KDTQHH4R0T',
  );
}
